name: Generate timetable markdown
on:
  workflow_dispatch:
jobs:
  generate-and-upload:
    name: Generate timetable markdown file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate
        run: |
          bash bin/generate_timetable
        env:
          NEXT_PUBLIC_NEWT_SPACE_UID: ${{ secrets.NEXT_PUBLIC_NEWT_SPACE_UID }}
          NEXT_PUBLIC_NEWT_API_TOKEN: ${{ secrets.NEXT_PUBLIC_NEWT_API_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: Timetable
          path: /tmp/timetable.md